# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
pod "AWSiOSSDKv2"
pod 'AWSCognito'
pod 'AWSDynamoDB'

target 'HangOut' do

end

target 'HangOutTests' do

end

